#!/usr/bin/env bash
set -e

usage() {
cat << EOF
test
EOF
}

awk \
  -f $(cd -P -- "$(dirname -- "$0")" && pwd -P)/tparts_build.awk \
  -v filename_value_entrypoint="$1" \
  -v path_values_index="$2"
