#!/usr/bin/env bash
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

# Include library scripts
PATH="$dir/../bin:$PATH"

# Set output directory
dir_dist="$dir/dist"

# Make dist directory
rm -rf "$dir_dist" && mkdir -p "$dir_dist"

# Build each document specified in generic documents directory in dist
for dir_src_document in $dir/documents/generic/*/; do
  echo "Building document $(basename $dir_src_document)"

  # Read document directory path from the document tparts_path value file
  file_tparts_path="$dir_src_document/tparts/tparts_path"

  if [ ! -f $file_tparts_path ]; then
    echo "$file_tparts_path is missing. Exiting."
    exit 1
  fi

  # Create document directory
  path_document="$dir_dist/$(cat $file_tparts_path)"
  
  # Create temporary value files directory
  mkdir -p "$path_document/tparts_tmp"

  # Build document body content HTML partials,
  # storing them as value files in the temporary directory
  if [[ "$(basename $dir_src_document)" -eq "index" ]]; then
    tparts_build \
      --template "$dir/templates/layout_index" \
      --values "$dir/templates/layout_index/tparts:$dir_src_document/tparts" > "$path_document/tparts_tmp/tparts_body_children.html"
  else
    tparts_build \
      --template "$dir/templates/layout_nested" \
      --values "$dir/templates/layout_nested/tparts:$dir_src_document/tparts" \
      > "$path_document/tparts_tmp/tparts_body_children.html"
  fi

  # Generate document HTML file from the document template and predefined and built value files
  tparts_build \
    --template "$dir/templates/document" \
    --values "$dir/tparts/generic:$dir_src_document/tparts:$path_document/tparts_tmp" \
    > "$path_document/index.html"

  # Remove temporary value files directory
  rm -rf "$path_document/tparts_tmp"

  # Copy document-related static files to the document directory
  cp -r $dir_src_document/static/* "$path_document"

  echo "Page $(basename $dir_src_document) has been built
  "
done

echo "All documents have been built in
$dir_dist"
