#!/usr/bin/env bash
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
path_dir_dist="$dir/dist"; rm -rf "$path_dir_dist" && mkdir -p "$path_dir_dist"
path_dir_dist_tmp="$dir/dist/tmp" && mkdir -p "$path_dir_dist_tmp"

function build_generic_document() {
  local path_dir_src_document="$1"

  echo "Building document $path_dir_src_document"

  local document_url_path=$(cat $(
    if [[ -f "$path_dir_src_document/_inline_path" ]]; then echo "$path_dir_src_document/_inline_path"; 
    else echo "$dir/values/_inline_path"; fi
  ))

  local document_filename=$(cat $(
    if [[ -f "$path_dir_src_document/_inline_filename" ]]; then echo "$path_dir_src_document/_inline_filename";
    else echo "$dir/values/_inline_filename"; fi
  ))

  echo "Server path: $document_url_path/$document_filename"

  local path_path_dir_dist_document="$path_dir_dist/$document_url_path"

  mkdir -p "$path_path_dir_dist_document"

  if [ -d $path_dir_src_document/static/ ]; then 
    cp -r $path_dir_src_document/static/* "$path_path_dir_dist_document"; fi 

  awk -f "$dir/../build_document.awk" -v path_output="$path_path_dir_dist_document/$document_filename" -v list_dir_values_paths="$dir/values/:$path_dir_src_document"

  echo "Document $path_dir_src_document has been built"
}

function build_sitemap() {
  echo "Building sitemap"
  mkdir -p "$path_dir_dist_tmp/sitemap"
  local path_dir_src_document="$dir/sitemap/document"

  local document_url_path=$(cat $(
    if [[ -f "$path_dir_src_document/_inline_path" ]]; then echo "$path_dir_src_document/_inline_path"; 
    else echo "$dir/values/_inline_path"; fi
  ))

  local document_filename=$(cat $(
    if [[ -f "$path_dir_src_document/_inline_filename" ]]; then echo "$path_dir_src_document/_inline_filename";
    else echo "$dir/values/_inline_filename"; fi
  ))

  awk -f "$dir/../build_document.awk" -v path_output="$path_dir_dist/$document_url_path/$document_filename" -v list_dir_values_paths="$dir/values/:$dir/sitemap/document:$path_dir_dist_tmp/sitemap/"

  echo "Sitemap has been built"
}

function build_generic_documents() {
  local path_dir_src_documents=$dir/documents/
  echo "Building generic documents from $path_dir_src_documents"

  for path_dir_src_document in $path_dir_src_documents/*/; do
    build_generic_document "$path_dir_src_document"

    local basename_path_dir_src_document=$(basename $path_dir_src_document)

    case "$basename_path_dir_src_document" in
      "robots.txt" | "404" | "403")
        ;;
      *) awk -f "$dir/../build_document.awk" -v path_output="$path_dir_dist_tmp/sitemap/_block_sitemap_children.xml" -v list_dir_values_paths="$dir/values/:$path_dir_src_document:$path_dir_src_sitemap_url"
        ;;
    esac
  done

  echo "Generic documents have been built"
}

build_generic_documents
build_sitemap

rm -rf "$path_dir_dist_tmp"
echo "All documents have been built in $path_dir_dist"
