image: debian

pages:
  stage: deploy
  script:
    - apt update
    - apt install gawk -y
    - echo "andis-sprinkis.gitlab.io" > ./site/_inline_domain
    - echo "tparts" > ./site/_inline_path_host_prefix
    - ./build
    - mv ./dist ./public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
