#!/usr/bin/env bash
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

usage() {
cat << EOF
test
EOF
}

awk \
  -f $dir/build_document.awk \
  -v filename_value_entrypoint="$1" \
  -v path_values_index="$2"
