#!/usr/bin/env bash

function resolve_values_paths() {
  # $@ - dir list

  declare -A tparts_values

  for path in "$@"; do
    for file_path in $(find "$path" -name "tparts_*"); do
      tparts_values[$(basename $file_path)]="$file_path"
    done
  done

  for index in "${!tparts_values[@]}"; do echo "$index:${tparts_values[$index]}"; done
}
