#!/usr/bin/env bash

function resolve_values_paths() {
  # $@ - dir list

  declare -A values_paths

  for path in "$@"; do
    for file_path in $(find "$path" -name "_*"); do
      values_paths[$(basename $file_path)]="$file_path"
    done
  done

  for index in "${!values_paths[@]}"; do echo "$index:${values_paths[$index]}"; done
}
