#!/usr/bin/env bash

function resolve_values_paths() {
  # $@ - dir list

  declare -A _values

  for path in "$@"; do
    for file_path in $(find "$path" -name "_*"); do
      _values[$(basename $file_path)]="$file_path"
    done
  done

  for index in "${!_values[@]}"; do echo "$index:${_values[$index]}"; done
}
