#!/usr/bin/env bash
set -e

usage() {
cat << EOF
usage: $0 FILE [-h|--help]

This script escapes HTML specific characters in a given file.

OPTIONS:
  FILE       Input file to read data and escape characters of.
  -h|--help  Show this message.
EOF
}

if [ -z "$1" ]; then usage; exit 1; fi

path_file="$1"

while [ ! $# -eq 0 ]; do
	case "$1" in
		-h|--help|?) usage; exit;;
	esac; shift
done

awk -f $(cd -P -- "$(dirname -- "$0")" && pwd -P)/escape_html.awk "$(readlink -f "$path_file")"
